### ISSUE TITLE
Actividad7-Diagrama de clases

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/actividad-7-diagrama-de-clases-modelo-blockchain-equipo-irving#3]
[Practica 7-Diagrama de clases-Equipo Irving.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-diagrama-de-clases-modelo-blockchain-equipo-irving/files/11551096/Practica.7-Diagrama.de.clases-Equipo.Irving.pdf)

**Comment by Heidi-19** [comment]
Calificación = 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
